server:
  port: 10000
  undertow:
    io-threads: 16
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
spring:
  #springboot 2.0 开始需要显示配置，否则报错
  main.allow-bean-definition-overriding: true
  application:
    name: rulesengine-service
    nameText: 规则平台服务
    #根据当前版本确定，用于swagger中显示服务版本号
    version: 1.0.0-SNAPSHOT